#!/usr/bin/env python3
"""
批量中文化 features 和 summary
处理 Type C（dict格式转字符串+翻译）和 Type B（混英翻译）
"""
import os
import re
import yaml

# 常用翻译词典（英文 → 中文）
TRANSLATIONS = {
    # 描述词
    "Preserve the core visual identity": "保留核心视觉特征",
    "A retro": "复古",
    "retro": "复古",
    "maximalist": "极繁主义",
    "minimalist": "极简主义",
    "bold": "粗壮/大胆",
    "clean": "干净",
    "warm": "温暖",
    "cool": "冷调",
    "soft": "柔和",
    "rough": "粗粝",
    "smooth": "平滑",
    "vibrant": "鲜艳",
    "muted": "柔和/低沉",
    "bright": "明亮",
    "dark": "暗黑",
    "light": "明亮",
    "heavy": "厚重",
    "lightweight": "轻盈",
    
    # 材质/质感
    "cream paper": "奶油纸",
    "paper background": "纸张背景",
    "paper field": "纸面",
    "paper grain": "纸张纹理",
    "hand-painted": "手绘",
    "hand-drawn": "手绘",
    "screen-print": "丝网印刷",
    "halftone": "半调",
    "marker": "马克笔",
    "oil-pastel": "油画棒",
    "crayon": "蜡笔",
    "pencil": "铅笔",
    "ink": "墨水",
    "watercolor": "水彩",
    "duotone": "双色",
    "monotone": "单色",
    "gradient": "渐变",
    "texture": "质感/纹理",
    "grain": "颗粒/纹理",
    "speckle": "细点",
    "bokeh": "散景",
    
    # 构图
    "central": "中央",
    "cropped": "裁切",
    "large in the": "放大在",
    "fills most of the frame": "占据画面大部分",
    "oversized": "超大",
    "background": "背景",
    "foreground": "前景",
    "middle frame": "画面中间",
    "lower third": "下方三分之一",
    "upper": "上方",
    "lower": "下方",
    "diagonal": "对角线",
    "symmetrical": "对称",
    "asymmetrical": "非对称",
    "layered": "分层",
    "composited": "合成",
    
    # 艺术风格词
    "editorial": "编辑设计",
    "collage": "拼贴",
    "doodle": "涂鸦",
    "sketch": "素描",
    "illustration": "插画",
    "poster": "海报",
    "portrait": "肖像",
    "landscape": "风景",
    "still life": "静物",
    "typography": "字体排版",
    "type poster": "字体海报",
    "mascot": "吉祥物",
    "character": "角色",
    "figure": "人物",
    "object": "物体",
    "scene": "场景",
    "background": "背景",
    
    # 颜色
    "navy": "藏青",
    "gray": "灰色",
    "ochre": "赭石",
    "mustard": "芥末黄",
    "coral": "珊瑚色",
    "teal": "青绿",
    "cyan": "青蓝",
    "turquoise": "绿松石",
    "emerald": "翠绿",
    "burgundy": "酒红",
    "maroon": "栗红",
    "cream": "奶油白",
    "ivory": "象牙白",
    "pearl": "珍珠白",
    "charcoal": "炭灰",
    "slate": "石板灰",
    "neon": "霓虹",
    "pastel": "粉彩",
    "monochrome": "单色",
    "chromatic": "彩色",
    "black and white": "黑白",
    
    # 光线
    "sunlight": "日光",
    "backlight": "逆光",
    "soft light": "柔光",
    "hard light": "硬光",
    "natural light": "自然光",
    "studio light": "棚拍光",
    "shadow": "阴影",
    "highlight": "高光",
    "glow": "光晕",
    
    # 物体/元素
    "cutout": "剪影/抠图",
    "silhouette": "轮廓剪影",
    "sticker": "贴纸",
    "bubble": "气泡",
    "splash": "飞溅",
    "foam": "泡沫",
    "ice": "冰块",
    "condensation": "水凝",
    "block letter": "块字",
    "serif": "衬线",
    "sans-serif": "无衬线",
    "hand-lettered": "手写字体",
    "block typography": "块状字体",
    "comic": "漫画",
    "manga": "漫画",
    "anime": "动漫",
    
    # 动作/状态
    "dynamic": "动态",
    "kinetic": "动势",
    "static": "静态",
    "frozen": "冻结",
    "liquid": "液态",
    "solid": "固态",
    "exploded": "爆炸",
    "cutaway": "剖面",
    "close-up": "近景",
    "wide-angle": "广角",
    "fisheye": "鱼眼",
    "macro": "微距",
    
    # 风格描述
    "scrapbook": "剪贴簿",
    "zine": "杂志",
    "PSA": "公益",
    "campaign": "推广",
    "KV": "主视觉",
    "thumbnail": "缩略图",
    "snapshot": "快照",
    "diary": "日记",
    "travel": "旅行",
    "festival": "节日",
    "sports": "运动",
    "music": "音乐",
    "food": "美食",
    "fashion": "时尚",
    "beauty": "美妆",
    "luxury": "奢侈",
    "streetwear": "街头",
    "Y2K": "Y2K",
    "grunge": "颓废",
    "hip-hop": "嘻哈",
    
    # 其他常用词
    "one": "一个",
    "single": "单个",
    "multiple": "多个",
    "limited": "限定",
    "dense": "密集",
    "sparse": "稀疏",
    "high contrast": "高对比",
    "low contrast": "低对比",
    "detailed": "精细",
    "simplified": "简化",
    "complex": "复杂",
    "geometric": "几何",
    "organic": "有机",
    "textural": "质感",
    "photographic": "摄影",
    "illustrative": "插画感",
    "toy": "玩具",
    "plush": "毛绒",
    "3D": "3D",
    "flat": "扁平",
    "2D": "2D",
    
    # 描述性短语
    "with": "，",
    "and": "、",
    "or": "或",
    "in": "在",
    "on": "在",
    "of": "的",
    "the": "",
    "a": "",
    "an": "",
    "is": "是",
    "are": "是",
    "as": "作为",
    "for": "用于",
    "from": "从",
    "into": "进入",
    "through": "穿过",
    "across": "横跨",
    "around": "环绕",
    "below": "下方",
    "above": "上方",
    "behind": "后方",
    "in front": "前方",
    
    # 句子结尾
    "style": "风格",
    "system": "系统",
    "mood": "氛围",
    "feeling": "感受",
    "energy": "气质",
    "texture": "质感",
    
    # 特殊词组
    "visible class of material": "可见材质的组合",
    "assembled into": "组装成",
    "target silhouette": "目标轮廓",
    "read clearly from a distance": "远距离可辨识",
    "remains legible up close": "近看依然清晰",
    "cushion-doll companion": "抱枕伙伴",
    "flat 2D": "扁平2D",
    "late-night": "深夜",
    "creative diary": "创意日记",
    "screen glow": "屏幕光",
    "handwritten doodle marks": "手绘涂鸦标记",
    "fuzzy plush": "毛绒",
    "circular backdrop": "圆形背景",
    "thick black shadow": "厚重黑色阴影",
    "doodle annotations": "涂鸦标注",
    "sticker labels": "贴纸标签",
    "lightning graphics": "闪电图形",
    "dense campaign microcopy": "密集推广文案",
    "toy-product poster": "玩具产品海报",
    "fashion photography": "时尚摄影",
    "halftone urban backgrounds": "半调城市背景",
    "cutout subject": "抠图主体",
    "sticker-like white edge": "贴纸式白边",
    "playful rounded block letters": "圆润可爱块字",
    "bright paper tile": "亮色纸片",
    "slightly rotated": "轻微旋转",
    "overlapping": "层叠",
    "Japanese city-travel": "日本城旅",
    "bold destination typography": "醒目目的地字体",
    "cute sticker elements": "可爱贴纸元素",
    "manga speech bubbles": "漫画气泡",
    "scrapbook editorial layout": "剪贴簿编辑排版",
    "neon kinetic typographic": "霓虹动势字体",
    "playful marker grounding": "活泼马克笔落地",
    "school grid paper cutout": "方格纸裁切",
    "olive scribble sports": "橄榄色涂鸦运动",
    "cyan red shockwave": "青红冲击波",
    "rough ink music doodle": "粗粝墨水音乐涂鸦",
    "metro doodle snapshot": "地铁涂鸦快照",
    "neon outdoor diary": "霓虹户外日记",
    "warm fisheye product": "暖调鱼眼产品",
    "blue hud macro creator": "蓝色HUD宏观创造者",
    "bold block mascot": "粗壮块状吉祥物",
    "blue lime kinetic comic": "蓝青柠动势漫画",
    "gothic cat doodle photo collage": "哥特猫涂鸦照片拼贴",
    "fantasy scribble mascot": "幻想涂鸦吉祥物",
    "analog editorial poster": "模拟编辑海报",
    "black cutout food card": "黑色镂空美食卡片",
    "tri color hardcut portrait": "三色硬切肖像",
    "blue halftone ransom zine": "蓝半调勒索杂志",
    "mono noir type portrait": "单色 noir 字体肖像",
    "naive marker quote card": "稚拙马克笔引语卡",
    "luxury street cover": "奢华街头封面",
    "folded newspaper product": "折叠报纸产品",
    "kinetic geometric doodle cutouts": "动势几何涂鸦裁切",
    "plush city festival mobile": "毛绒城市节日动态",
    "blue bubble fisheye action": "蓝气泡鱼眼动感",
    "sunny 3D avatar campaign": "阳光3D虚拟形象推广",
    "rough marker monster": "粗粝马克笔怪兽",
    "photo illustration overlay": "照片插画叠加",
    "subway doodle photo hybrid": "地铁涂鸦照片混合",
    "neon doodle gallery snapshot": "霓虹涂鸦画廊快照",
    "urban transit doodle diary": "城郊涂鸦日记",
    "k pop apocalypse ransom zine": "K-pop末日勒索杂志",
    "y2k grunge hiphop cutout": "Y2K颓废嘻哈裁切",
    "y2k mirror ui scribble collage": "Y2K镜像UI涂鸦拼贴",
    "yellow black manga food zine": "黄黑漫画美食杂志",
    "plush comic toy product": "毛绒漫画玩具产品",
    "plush city festival mobile poster": "毛绒城市节日起草海报",
    "turquoise red techno manga": "绿松石红科技漫画",
    "impact burst halftone comic": "冲击爆发半调漫画",
    "sky blue home life doodle": "天蓝家居涂鸦",
    "bold anime reaction thumbnail": "粗壮动漫反应缩略图",
    "playful mascot doodle snapshot": "活泼吉祥物涂鸦快照",
    "pop bubble letter photo": "流行气泡字照片",
    "market brush produce poster": "市集笔刷产品海报",
    "neon diary collage": "霓虹日记拼贴",
    "tokyo kawaii travel collage poster": "东京可爱旅行拼贴海报",
    "neon kinetic typographic poster": "霓虹动势字体海报",
    "blue kinetic poster": "蓝动势海报",
    "bold block mascot poster": "粗壮块状吉祥物海报",
    "fisheye bubble poster": "鱼眼气泡海报",
    "chromatic fisheye orbit pop": "彩色鱼眼轨道流行",
    "sky blue home life doodle poster": "天蓝家居涂鸦海报",
    "olive scribble sports poster": "橄榄色涂鸦运动海报",
    "blue hud macro product poster": "蓝色HUD宏观产品海报",
    "analog editorial poster": "模拟编辑海报",
    "rough ink music doodle poster": "粗粝墨水音乐涂鸦海报",
    "neon outdoor diary longform collage": "霓虹户外日记长幅拼贴",
    "soft analog future editorial": "柔和模拟未来编辑",
    "blue lime kinetic comic type poster": "蓝青柠动势漫画字体海报",
    "kinetic luxury street fashion cover": "动势奢华街头时尚封面",
    "naive marker quote card style": "稚拙马克笔引语卡风格",
    "kinetic geometric doodle cutouts": "动势几何涂鸦裁切",
    "neon plush gadget pop 3d": "霓虹毛绒配件流行3D",
    "sunburst fisheye bubble type poster": "日光鱼眼气泡字体海报",
    "soft analog future editorial poster": "柔和模拟未来编辑海报",
    "school grid paper cutout poster": "方格纸裁切海报",
    "metro doodle snapshot diary": "地铁涂鸦快照日记",
    "warm fisheye product impact ad": "暖调鱼眼产品冲击广告",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot": "霓虹涂鸦画廊快照",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid": "地铁涂鸦照片混合",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster": "霓虹动势字体海报",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster": "东京可爱旅行拼贴海报",
    "plush city festival mobile poster": "毛绒城市节日起草海报",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster": "蓝色HUD宏观创造者科技海报",
    "neon kinetic typographic poster": "霓虹动势字体海报",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster": "照片插画叠加海报",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道流行海报风格",
    "rough ink music doodle poster style": "粗粝墨水音乐涂鸦海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "analog editorial poster style": "模拟编辑海报风格",
    "black cutout food card ad style": "黑色镂空美食卡片广告风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "kinetic geometric doodle cutouts style": "动势几何涂鸦裁切风格",
    "neon plush gadget pop 3d style": "霓虹毛绒配件流行3D风格",
    "sunburst fisheye bubble type poster style": "日光鱼眼气泡字体海报风格",
    "metro doodle snapshot diary style": "地铁涂鸦快照日记风格",
    "warm fisheye product impact ad style": "暖调鱼眼产品冲击广告风格",
    "blue bubble fisheye action poster style": "蓝气泡鱼眼动感海报风格",
    "gothic cat doodle photo collage style": "哥特猫涂鸦照片拼贴风格",
    "fantasy scribble mascot poster style": "幻想涂鸦吉祥物海报风格",
    "sunny 3d avatar campaign style": "阳光3D虚拟形象推广风格",
    "neon doodle gallery snapshot style": "霓虹涂鸦画廊快照风格",
    "tri color hardcut portrait poster style": "三色硬切肖像海报风格",
    "subway doodle photo hybrid style": "地铁涂鸦照片混合风格",
    "k-pop apocalypse ransom zine style": "K-Pop末日勒索杂志风格",
    "urban transit doodle diary style": "城郊涂鸦日记风格",
    "y2k mirror ui scribble collage style": "Y2K镜像UI涂鸦拼贴风格",
    "yellow black manga food zine ad style": "黄黑漫画美食杂志广告风格",
    "plush comic toy product poster style": "毛绒漫画玩具产品海报风格",
    "blue halftone ransom zine poster style": "蓝半调勒索杂志海报风格",
    "mono noir type portrait poster style": "单色 noir 字体肖像海报风格",
    "folded newspaper product ad style": "折叠报纸产品广告风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "kinetic luxury street fashion cover style": "动势奢华街头时尚封面风格",
    "neon diary collage style": "霓虹日记拼贴风格",
    "impact burst halftone comic poster style": "冲击爆发半调漫画海报风格",
    "sky blue home life doodle poster style": "天蓝家居涂鸦海报风格",
    "tokyo kawaii travel collage poster style": "东京可爱旅行拼贴海报风格",
    "plush city festival mobile poster style": "毛绒城市节日起草海报风格",
    "y2k grunge hiphop cutout poster style": "Y2K颓废嘻哈裁切海报风格",
    "bold anime reaction thumbnail style": "粗壮动漫反应缩略图风格",
    "playful marker grounding poster style": "活泼马克笔落地海报风格",
    "playful mascot doodle snapshot style": "活泼吉祥物涂鸦快照风格",
    "pop bubble letter photo poster style": "流行气泡字照片海报风格",
    "market brush produce poster style": "市集笔刷产品海报风格",
    "blue hud macro creator tech poster style": "蓝色HUD宏观创造者科技海报风格",
    "neon kinetic typographic poster style": "霓虹动势字体海报风格",
    "turquoise red techno manga poster style": "绿松石红科技漫画海报风格",
    "rough marker monster poster style": "粗粝马克笔怪兽海报风格",
    "photo illustration overlay poster style": "照片插画叠加海报风格",
    "blue kinetic poster style": "蓝动势海报风格",
    "bold block mascot poster style": "粗壮块状吉祥物海报风格",
    "fisheye bubble poster style": "鱼眼气泡海报风格",
    "chromatic fisheye orbit pop poster style": "彩色鱼眼轨道